import { ToolHandler } from '../../utils/types.js';
import { z } from 'zod';
import { getContractAddress } from 'viem';

export const name = 'get_contract_address';

export const description =
  'Get the contract address that would be generated by a contract deployment transaction';

export const paramsSchema = {
  from: z
    .string()
    .optional()
    .describe('The address the contract was deployed from'),
  nonce: z
    .number()
    .optional()
    .describe('The nonce of the transaction which deployed the contract'),
  opcode: z
    .enum(['CREATE', 'CREATE2'])
    .optional()
    .default('CREATE')
    .describe('The opcode to invoke the contract deployment'),
  bytecode: z
    .string()
    .optional()
    .describe("The to-be-deployed contract's bytecode (only for CREATE2)"),
  bytecodeHash: z
    .string()
    .optional()
    .describe(
      "A hash of the to-be-deployed contract's bytecode (only for CREATE2)"
    ),
  salt: z
    .string()
    .optional()
    .describe('An arbitrary value provided by the sender (only for CREATE2)'),
};

export const handler: ToolHandler<typeof paramsSchema> =
  (context) => async (args) => {
    try {
      // Validate CREATE2 required parameters
      if (args.opcode === 'CREATE2') {
        if (!args.bytecode && !args.bytecodeHash) {
          throw new Error(
            'Either bytecode or bytecodeHash must be provided for CREATE2 opcode'
          );
        }
        if (!args.salt) {
          throw new Error('salt must be provided for CREATE2 opcode');
        }
      }

      // Validate CREATE required parameters
      if (args.opcode === 'CREATE') {
        if (!args.from || !args.nonce) {
          throw new Error('from and nonce must be provided for CREATE opcode');
        }
      }

      // Process inputs for viem
      const params: any = {
        opcode: args.opcode,
      };

      if (args.from) {
        params.from = args.from;
      }

      if (args.nonce !== undefined) {
        params.nonce = BigInt(args.nonce);
      }

      if (args.bytecode) {
        params.bytecode = args.bytecode;
      }

      if (args.bytecodeHash) {
        params.bytecodeHash = args.bytecodeHash;
      }

      if (args.salt) {
        params.salt = args.salt;
      }

      const address = getContractAddress(params);

      return {
        content: [
          {
            type: 'text',
            text: JSON.stringify({
              contractAddress: address,
            }),
          },
        ],
      };
    } catch (error) {
      throw error instanceof Error
        ? error
        : new Error('Failed to compute contract address');
    }
  };
